### PR TITLE
[JENKINS-39154] Restore ACE editor

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-39154](https://issues.jenkins-ci.org/browse/JENKINS-39154)

Rejects https://github.com/jenkinsci/plugin-pom/pull/36 until I can get an explanation from @tfennelly on how this plugin should be updated.

@reviewbybees ASAP

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
:bee: Given that this is a temporary fix

**Comment by andresrc** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Comment by stephenc** [comment]
:bee:

**Pull request merged**
