### PR TITLE
Dark, but not Dark (System), theme support

### PR DESCRIPTION
**Pull request by basil**
Fixes https://github.com/jenkinsci/dark-theme-plugin/issues/127. Can be merged and released as-is without any regressions, but depends on https://github.com/jenkinsci/dark-theme-plugin/pull/319 for the fix to actually take effect. I tested this by running in both the dark and light theme and verifying that the background was adjusted appropriately.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
This looks great for Dark theme.

image

I'm unsure if Dark system theme should have been implemented with the property, I never finished the work for system themes to report whether the user wants a light or a dark theme.

Currently if a system has a dark-system theme setup and the user has light mode they see a dark editor:

image

----

I will try get back to this work, I had an idea for the API for it but this was a few months ago 😢

**Comment by basil** [comment]
No action items for me as far as I can tell.

**Review by timja — APPROVED** [review]
Dark system theme issue resolved via https://github.com/jenkinsci/dark-theme-plugin/pull/324.

Looks great to me

**Comment by timja** [comment]
(system theme support work will be continued in https://github.com/jenkinsci/theme-manager-plugin/pull/171 and will need changes in this plugin but that can be added on top)

**Comment by basil** [comment]
> Dark system theme issue resolved via [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324).

https://github.com/jenkinsci/dark-theme-plugin/pull/324 made things worse, not better. After https://github.com/jenkinsci/dark-theme-plugin/pull/319 but before https://github.com/jenkinsci/dark-theme-plugin/pull/324 I get the same results with this PR as https://github.com/jenkinsci/workflow-cps-plugin/pull/654#pullrequestreview-1287070582. After https://github.com/jenkinsci/dark-theme-plugin/pull/324 the effect of this PR is the same as the effect without it (i.e., no dark theme is ever displayed). In other words, https://github.com/jenkinsci/dark-theme-plugin/pull/324 completely nullifies the effect of this set of changes, which is clearly undesirable.

**Comment by timja** [comment]
> > Dark system theme issue resolved via [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324).
> 
> [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324) made things worse, not better. After [jenkinsci/dark-theme-plugin#319](https://github.com/jenkinsci/dark-theme-plugin/pull/319) but before [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324) I get the same results with this PR as [#654 (review)](https://github.com/jenkinsci/workflow-cps-plugin/pull/654#pullrequestreview-1287070582). After [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324) the effect of this PR is the same as the effect without it (i.e., no dark theme is ever displayed). In other words, [jenkinsci/dark-theme-plugin#324](https://github.com/jenkinsci/dark-theme-plugin/pull/324) completely nullifies the effect of this set of changes, which is clearly undesirable.

If you select "Dark" and not "Dark (system)" you should get the same behaviour as before.

This PR introduced a regression for "Dark (system)" users who use a light appearance on their system.

The existing theme manager API for this doesn't support system respecting themes. i.e. if you use the API as-is you would get behaviour like:

image

https://github.com/jenkinsci/theme-manager-plugin/pull/171 is the beginnings of an API that will support system respecting themes properly.

**Comment by basil** [comment]
OK I understand your point and can reproduce your results. So as-is, this PR is a strict improvement over the status quo without introducing any regressions and is therefore ready for merge. To clarify the (confusing) state of affairs I renamed the title of the PR to

> Dark, but not Dark (System), theme support

**Comment by basil** [comment]
I pushed a few commits including one to make `theme-manager` optional and fall back gracefully to the old behavior when it is not installed. I tested this by running this PR both with and without `theme-manager` and confirmed no stack traces were printed in the logs.

**Review by car-roll — APPROVED** [review]

**Comment by timja** [comment]
system theme support in https://github.com/jenkinsci/workflow-cps-plugin/pull/654

**Pull request merged**
