### PR TITLE
ReplayFlowFactoryAction - Adding getters and making class public

### PR DESCRIPTION
**Pull request by aytuncbeken**
Hi,

Currently I am working on Pipeline As Yaml Plugin which is having problem when Replay is used. 
I need to get ReplayFlowFactoryAction from actions and replacementMainScript to pass new script to CPS FLow execution in Pipelien As Yaml.

Thanks

### CODE REVIEW

**Review by dwnusbaum — COMMENTED** [review]
@aytuncbeken Do you have a linked PR to `pipeline-as-yaml` demonstrating that this PR fixes the issue so we can validate the change?

**Comment by aytuncbeken** [comment]
Hi @dwnusbaum ,
I have the branch where I have pushed the changes I want to make. As the class is not public and don't have getter methods, I can not fix it now. However, I have prepared the branch and a screenshot to show what I want to do.
Please check here -> https://github.com/jenkinsci/pipeline-as-yaml-plugin/blob/pipeline-as-yaml-plugin-32/src/main/java/io/jenkins/plugins/pipeline/cps/PipelineCpsFlowDefinition.java#L34-L41
Screenshot 2021-01-23 at 21 06 13

**Comment by bitwiseman** [comment]
@aytuncbeken 
You can create a PR against `pipeline-as-yaml` using the incremental build from this PR.  

Screen Shot 2021-01-25 at 8 57 24 AM

https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/workflow/workflow-cps/2.88-rc2581.d835a43bd260/

**Comment by dwnusbaum** [comment]
I am closing this. Feel free to resolve any merge conflicts and reopen it with a link to another PR that demonstrates the use case if you are still interested in this change.

**Pull request closed without merging**
