### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@reviewbybees any one can help me see this

**Comment by LinuxSuRen** [comment]
@jglick

**Comment by oleg-nenashev** [comment]
Merging does not work well in WebUI. it does not update the mergeability status sometimes

**Comment by LinuxSuRen** [comment]
@oleg-nenashev ui conflict already fixed.

**Comment by LinuxSuRen** [comment]
Any issues?

**Comment by oleg-nenashev** [comment]
Requested reviews from the current maintainers. Sorry, I have no time for reviews this week due to JEP-200

**Pull request merged**
