### PR TITLE
[FIXED JENKINS-44924] Add support for .sort, .unique, etc

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-44924](https://issues.jenkins-ci.org/browse/JENKINS-44924)

Downstream of https://github.com/cloudbees/groovy-cps/pull/86 and https://github.com/jenkinsci/script-security-plugin/pull/191

cc @reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
@abayer Doesn't really seem much point reviewing a dependency bump until tests pass though, eh?

**Comment by abayer** [comment]
@svanoort Fair point. =) Marking as WIP.

**Comment by bitwiseman** [comment]
@abayer Do you think you'll get back to this? If not,  could you close?

**Comment by dwnusbaum** [comment]
Closing, see https://github.com/cloudbees/groovy-cps/pull/86#issuecomment-1291162992.

**Pull request closed without merging**
