### PR TITLE
Consume temporary version of groovy-cps that reduces memory

### PR DESCRIPTION
**Pull request by svanoort**
Demonstrates that https://github.com/cloudbees/groovy-cps/pull/74 works and does not introduce errors.

### CODE REVIEW

**Comment by svanoort** [comment]
Sigh, rebuild for what looks like builder issues

**Comment by svanoort** [comment]
Passes locally, doing something to trigger a rebuild so we can see if it goes 💥  in CI.

**Comment by jglick** [comment]
Regarding the Surefire error attributed (perhaps falsely) to `WorkflowJobNonRestartingTest`: not sure what went on.

    lineNumber: 2524917

suggests perhaps a huge list of repeating error messages. The [relevant log](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-176/1/execution/node/94/log/) ends with

```
00:29:52.616 [INFO] Running org.jenkinsci.plugins.workflow.cps.DSLTest
00:34:15.943 Sending interrupt signal to process
```

which suggests a hung test. In that case you would want to pick up https://github.com/jenkinsci/jenkins-test-harness/pull/67, most easily by just updating to the 2.35 parent POM.

**Comment by abayer** [comment]
Closing in favor of #177

**Pull request closed without merging**
