### PR TITLE
Support PCT for multi-module Maven projects (II)

### PR DESCRIPTION
**Pull request by jglick**
Subsumes #685 but should allow https://github.com/jenkins-infra/repository-permissions-updater/pull/3210 to be reverted, cleaning up technical debt from #612. Local testing seems fine using both a clean working copy and a clean local repo:

```bash
mvn clean test -Dtest=CpsDefaultGroovyMethodsTest
```

### CODE REVIEW

**Review by basil — CHANGES_REQUESTED** [review]
Failed PCT against the `multimodule` project branch. Note that #685 passes.

- https://github.com/jenkinsci/bom/pull/1899
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-1899/2/consoleFull

What goal are you trying to achieve by continuing to dig into this?

**Comment by jglick** [comment]
`mvn test` worked but `mvn surefire:test` (even after previous compilation) did not; I think I have fixed that.

**Review by basil — APPROVED** [review]
The latest revision passes local PCT testing for me on the `multimodule` project branch. Still not sure it was worth the effort.

**Review by dwnusbaum — APPROVED** [review]

**Comment by jglick** [comment]
https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3651.ve2e99a_4f4a_e5

**Comment by basil** [comment]
Breaks the `master` branch of PCT, _unlike_ my original proposal from #685 (which works on both the `master` and `multimodule` branches of PCT). Can be seen by running `PLUGINS=workflow-cps TEST=InjectedTest bash local-test.sh` in https://github.com/jenkinsci/bom/pull/1903.

I suggest that you either figure out how to get your code to work on both PCT branches or that you accept my original submission (which does work on both branches), even if you consider it "undesirable". You can always switch back to your code once the PCT multimodule project has been integrated.

**Pull request merged**
