### PR TITLE
[JENKINS-31840] Adds a Support component for Pipeline build thread dumps

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-31840](https://issues.jenkins-ci.org/browse/JENKINS-31840)

Based on work by @christ66.

@reviewbybees

### CODE REVIEW

**Comment by christ66** [comment]
🐝

**Comment by svanoort** [comment]
🐝

**Comment by christ66** [comment]
🐝

**Comment by svanoort** [comment]
🐝

**Pull request merged**
