### PR TITLE
[JENKINS-27421] Improve behavior of map iteration workaround a bit

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-27421](https://issues.jenkins-ci.org/browse/JENKINS-27421)

Downstream of https://github.com/jenkinsci/script-security-plugin/pull/92.

@reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
:bee:

**Comment by stephenc** [comment]
:bee:

**Comment by svanoort** [comment]
🐝  LGTM assuming tests pass

**Comment by raul-arabaolaza** [comment]
:bee:

**Pull request merged**
