### PR TITLE
Robustness of `CpsFlowExecution.getNode`

### PR DESCRIPTION
**Pull request by jglick**
Same stack trace as in https://github.com/jenkinsci/workflow-job-plugin/pull/300. Somewhere the build is corrupt in this case; unclear how, but a `NullPointerException` is not appropriate.

### CODE REVIEW

**Comment by jglick** [comment]
Also observed

```
java.lang.IllegalStateException: List of flow heads unset for CpsFlowExecution[null]
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getCurrentHeads(CpsFlowExecution.java:985)
	at org.jenkinsci.plugins.workflow.flow.FlowExecution.isComplete(FlowExecution.java:208)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.isComplete(CpsFlowExecution.java:1241)
	at org.jenkinsci.plugins.workflow.cps.RunningFlowActions.createFor(RunningFlowActions.java:52)
	at org.jenkinsci.plugins.workflow.cps.RunningFlowActions.createFor(RunningFlowActions.java:42)
	at hudson.model.Actionable.createFor(Actionable.java:115)
	at hudson.model.Actionable.getActions(Actionable.java:140)
	at hudson.model.Run.getBadgeActions(Run.java:747)
```

but this is not thrown up: https://github.com/jenkinsci/workflow-cps-plugin/blob/ee82cc1f195b338de9b2a21b3684b2a4090d77bb/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L993-L996

**Comment by jglick** [comment]
(CB ref.: BEE-24000)

**Comment by jglick** [comment]
also

```
WARNING	o.j.p.w.cps.CpsFlowExecution#onProgramEnd: Error trying to end execution CpsFlowExecution[Owner[…]]
java.lang.NullPointerException
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getFirstHead(CpsFlowExecution.java:1494)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onProgramEnd(CpsFlowExecution.java:1266)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:444)
```

**Review by jtnord — APPROVED** [review]

**Review by car-roll — APPROVED** [review]

**Comment by dwnusbaum** [comment]
Just for the record, it would be nice to hold off on merges for a little bit while https://github.com/jenkinsci/workflow-cps-plugin/pull/612 is in flight. Getting the PCT working with that PR is taking a bit more time than I expected.

**Comment by dwnusbaum** [comment]
Interestingly, `git merge master` on the command line handled the merge correctly without any issues, but GitHub didn't offer the button to do it automatically.

I'm going to merge this and release the plugin.

**Review by dwnusbaum — APPROVED** [review]

**Pull request merged**
