### PR TITLE
Make DSL compilable under -source 8 with some versions of javac

### PR DESCRIPTION
**Pull request by jglick**
No semantic change, just makes it easier to experiment with targeting 2.60+ cores.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees done

**Comment by svanoort** [comment]
@jglick Closing-opening to try to retrigger

**Comment by abayer** [comment]
I already retriggered this and https://github.com/jenkinsci/pipeline-stage-step-plugin/pull/12 =)

**Comment by svanoort** [comment]
ah, thanks @abayer

**Pull request merged**
