### PR TITLE
[JEP-210] Integration testing

### PR DESCRIPTION
**Pull request by jglick**
My own version of #251. Picks up https://github.com/jenkinsci/workflow-job-plugin/pull/27, #253, #254,  and https://github.com/jenkinsci/structs-plugin/pull/41.

### CODE REVIEW

**Comment by jglick** [comment]
Actually from a quick glance it looks like `StepNodeTest` failures are legitimate; looking.

**Comment by jglick** [comment]
Regarding `PersistenceProblemsTest`, I am indeed getting some failures locally which might reflect regressions, or might be flaky test issues etc.:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.assertCompletedCleanly(PersistenceProblemsTest.java:77)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:115)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:121)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.lambda$completedNoNodesPersisted$5(PersistenceProblemsTest.java:189)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.assertCompletedCleanly(PersistenceProblemsTest.java:77)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:115)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:121)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.lambda$completedButWrongDoneStatus$7(PersistenceProblemsTest.java:210)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.assertCompletedCleanly(PersistenceProblemsTest.java:77)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:115)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.runBasicBuild(PersistenceProblemsTest.java:121)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.lambda$completedFinalFlowNodeNotPersisted$3(PersistenceProblemsTest.java:164)
```

I am not sure how seriously to take these since I get a _different_ test failure when I simply use the same Jenkins core baseline and the most recent released deps of the affected plugins:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.assertCompletedCleanly(PersistenceProblemsTest.java:59)
	at org.jenkinsci.plugins.workflow.cps.PersistenceProblemsTest.lambda$inProgressButProgramLoadFailure$19(PersistenceProblemsTest.java:321)
```

In other words, we have a situation where PCT is not getting regularly run here, and at least some failures are not related to JEP-210.

**Comment by svanoort** [comment]
@jglick PersistenceProblemsTests should be taken very seriously indeed.  For me, if I use workflow-job 2.25 and everything else the same, these tests pass.  And unfortunately they still fail with my AsynchronousExecution fix applied (so far), which suggests something deeper is amiss.

**Comment by svanoort** [comment]
(Note only reason I'm not approving is because it needs to be converted to something backported for merge there)

**Comment by jglick** [comment]
(and it is only a `test`-scoped dep anyway)

**Pull request merged**
