### PR TITLE
groovy-cps 1.11

### PR DESCRIPTION
**Pull request by jglick**
[Changes](https://github.com/cloudbees/groovy-cps/compare/groovy-cps-1.10...groovy-cps-1.11)

@reviewbybees esp. @kohsuke

### CODE REVIEW

**Comment by svanoort** [comment]
🐝

**Comment by oleg-nenashev** [comment]
Uhm, I'm not sure it is a bug...

`Env#getLocalVariableType()` is a new method introduced in the interface. Smells like a binary compat issue, which may widespread to dependencies. 

I see no usages in OSS packages, but I still feel uncomfortable after the Stapler fun.

**Comment by oleg-nenashev** [comment]
^^ CC @svanoort , who introduced it in https://github.com/cloudbees/groovy-cps/commit/e7368eae7facfeb1676a1d5af93347748e524c0b

**Comment by jglick** [comment]
> binary compat issue, which may widespread to dependencies.
> 
> I see no usages in OSS packages

`groovy-cps` should be used only internally in this plugin.

**Comment by jglick** [comment]
In other words, we need to be concerned about compatibility in the serialized form, but not in Java signatures.

**Comment by oleg-nenashev** [comment]
@jglick If it's not supposed to be used, there are Maven shading features for it. But feel free to go forward as a maintainer

**Comment by jglick** [comment]
> there are Maven shading features for it

A possibility, but not so easy, since we would need to update serialized data too.

**Comment by jglick** [comment]
Anyway in this case the Javadoc states clearly:

> This interface is not to be implemented outside this library.

**Pull request merged**
