### PR TITLE
[JENKINS-47105] Fixing test failure in loaderReleased

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-47105](https://issues.jenkins-ci.org/browse/JENKINS-47105)

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Probably a good candidate for squashing, since some of the intermediate commits are deliberately junk.

**Comment by jglick** [comment]
Hmm, [this](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-178/3/execution/node/102/log/) does not look good…

**Comment by jglick** [comment]
Nor does [this](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-178/3/execution/node/60/log/).

**Comment by svanoort** [comment]
AFAICT it looks reasonable, assuming tests pass -- though it does seem to be running awfully long.

**Comment by svanoort** [comment]
I take it back, that last one looks scary though it *could* be some flakiness in CI.  The tests shouldn't take so long to run though -- something is off.

**Comment by jglick** [comment]
Indeed something is off. I thought I had diagnosed the issue but it does not seem that I did.

**Comment by jglick** [comment]
I now think https://github.com/jenkinsci/jenkins-test-harness/pull/67 is responsible for the problem, but have not yet figured out why.

**Comment by jglick** [comment]
Hmm. Locally, the test passes if _either_ I stop running `trustedShell` first, _or_ I revert that test timeout change. But on CI it continues to fail _sometimes_ even when I stop running `trustedShell` first.

**Comment by jglick** [comment]
Looking better. Seems that whatever leaked, the leaks persist across Surefire reused forks of the JVM. Safer to have each test suite run completely independently, even if it adds a bit of overhead.

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
