### PR TITLE
[JENKINS-58501] Update to groovy-cps 1.30

### PR DESCRIPTION
**Pull request by dwnusbaum**
See [JENKINS-58501](https://issues.jenkins-ci.org/browse/JENKINS-58501).

Picks up https://github.com/cloudbees/groovy-cps/pull/99 from @steven-terrana to suppress the mismatch warnings for some kinds of metaprogramming that confuse the mismatch detection code.

### CODE REVIEW

**Comment by jglick** [comment]
Should this back out #305?

**Comment by dwnusbaum** [comment]
@jglick see https://github.com/jenkinsci/workflow-cps-plugin/pull/305#issuecomment-514667427. I didn't notice that #306 included #305 but then reverted it, and did not squash-merge, so GitHub thinks #305 was merged, which is not technically wrong, but it was immediately reverted by the next commit in #306.

**Comment by jglick** [comment]
So the upshot is that the next release will not include the unnecessary new API? Fine.

**Comment by dwnusbaum** [comment]
> So the upshot is that the next release will not include the unnecessary new API?

Yes, the new API will not be available in the next release and was never available from `HEAD` of `master` at any point, it just _looks_ like it was merged because the [commit](4e4e3ed) in #305 was also in #306 (along with the [commit](e7319b7) to revert #305), so when #306 got merged GitHub automatically marked #305 as merged (technically right but very confusing). Would not have been so confusing if #306 was based on `master` instead of on #305 or if I had squash-merged #306 so that the addition and reversion were cancelled out before they hit `master`.

**Pull request merged**
