### PR TITLE
[FIXED JENKINS-44619] Don't allow replays of nonbuildable jobs

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-44619](https://issues.jenkins-ci.org/browse/JENKINS-44619)

cc @reviewbybees

### CODE REVIEW

**Comment by abayer** [comment]
@jglick What error would you recommend?

**Comment by jglick** [comment]
> What error would you recommend?

Could use a 409, as [here](https://github.com/jenkinsci/jenkins/blob/f09d00dd32ea351105ef99456f3af1883d3ca8da/core/src/main/java/jenkins/model/ParameterizedJobMixIn.java#L196-L198).

**Comment by abayer** [comment]
@svanoort Updated to throw an http error.

**Comment by svanoort** [comment]
@abayer Looking good here!

**Pull request merged**
