### PR TITLE
Test case for JENKINS-57253

### PR DESCRIPTION
**Pull request by basil**
Adding a test case for [JENKINS-57253](https://issues.jenkins-ci.org/browse/JENKINS-57253). The last assertion currently fails due to a leaked executor, as described in the bug, so I have marked the test with `@Ignore`. When the bug is fixed, the `@Ignore` annotation can be removed.

### CODE REVIEW

**Comment by dwnusbaum** [comment]
See https://github.com/jenkinsci/workflow-cps-plugin/pull/356 for the fix.

**Comment by dwnusbaum** [comment]
Also, did you happen to check whether things work correctly if you do put a `loop` or `switch` around the `node` step? If that causes problems, then we also need some kind of runtime behavior change in groovy-cps.

**Comment by basil** [comment]
Thank _you_ for the fix!

> Actually, I am pretty sure that `break` would be disallowed in something like `for { node { break; } }` because the closure is a new scope as far as `break` and `continue` are concerned.

Indeed, I confirmed that `for { node { break; } }` fails at the compilation stage as you predicted.

**Comment by car-roll** [comment]
@basil fyi I merged https://github.com/cloudbees/groovy-cps/pull/109 but I don't think it's getting released until we get the repo moved into `jenkinsci`.
I noticed that this test did not have an `@Ignore`. Is this issue already fixed via some other way?

**Comment by basil** [comment]
> @basil fyi I merged [cloudbees/groovy-cps#109](https://github.com/cloudbees/groovy-cps/pull/109) but I don't think it's getting released until we get the repo moved into `jenkinsci`. I noticed that this test did not have an `@Ignore`. Is this issue already fixed via some other way?

Sorry, when I was merging with `master` I accidentally added some unrelated changes to this. I just corrected that. It now has the right set of changes with `@Ignore`.

**Comment by car-roll** [comment]
@basil what  confused  me though was that the checks showed green. Did this test actually  pass without any fix?

**Comment by basil** [comment]
> @basil what confused me though was that the checks showed green. Did this test actually pass without any fix?

They were green because I had posted an unrelated set of changes that happened to pass.

**Review by car-roll — APPROVED** [review]

**Pull request merged**
