### PR TITLE
[JENKINS-31842] Thread dump improvements

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/7 and https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/9 and https://github.com/jenkinsci/workflow-step-api-plugin/pull/4.

@reviewbybees

### CODE REVIEW

**Comment by svanoort** [comment]
🐝  LGTM

**Comment by abayer** [comment]
:bee:

**Comment by svanoort** [comment]
🐝

**Comment by kohsuke** [comment]
:bee:

**Comment by svanoort** [comment]
🐝

**Pull request merged**
