### PR TITLE
[INFRA-1139] Using yarn

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/plugin-pom/pull/57.

I really have no idea what I am doing here, I am just desperate for my builds to not be broken by random npm network errors, as discussed in [INFRA-1139](https://issues.jenkins-ci.org/browse/INFRA-1139), for example [this one](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/PR-124/6/execution/node/78/log/):

```
[ERROR] npm ERR! Windows_NT 6.3.9600
[ERROR] npm ERR! argv "C:\\Jenkins\\workspace\\_workflow-cps-plugin_PR-124-QA73AXUOYU7624A6FJBQP7IO65ZTW6X6EMWWBTMDNC4JMMROOEBA\\node\\node.exe" "C:\\Jenkins\\workspace\\_workflow-cps-plugin_PR-124-QA73AXUOYU7624A6FJBQP7IO65ZTW6X6EMWWBTMDNC4JMMROOEBA\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v4.0.0
[ERROR] npm ERR! npm  v2.13.1
[ERROR] npm ERR! code ECONNRESET
[ERROR] npm ERR! errno ECONNRESET
[ERROR] npm ERR! syscall read
[ERROR] 
[ERROR] npm ERR! network read ECONNRESET
[ERROR] npm ERR! network This is most likely not a problem with npm itself
[ERROR] npm ERR! network and is related to network connectivity.
[ERROR] npm ERR! network In most cases you are behind a proxy or have bad network settings.
[ERROR] npm ERR! network 
[ERROR] npm ERR! network If you are behind a proxy, please make sure that the
[ERROR] npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

@reviewbybees esp. @cliffmeyers (somehow I cannot request a review from you directly)

### CODE REVIEW

**Comment by jglick** [comment]
OTOH https://github.com/jenkinsci/blueocean-plugin/pull/981 is on hold, so…?

**Comment by jglick** [comment]
> use the Artifactory mirror from Jenkins CI. If you'd like to give that a try, I can give you the steps.

Is that mirror set up? If so, yes by all means I would like to try that. Anything to reduce our dependence on external servers.

**Comment by jglick** [comment]
Maybe by

```bash
PATH=$(pwd)/node:$PATH npm config set registry https://repo.jenkins-ci.org/api/npm/npm/
rm yarn.lock
mvn -DskipTests clean install
```

??

**Comment by cliffmeyers** [comment]
I would suggest using yarn's config mechanism instead:

`yarn config set -- --registry https://repo.jenkins-ci.org/api/npm/npm/`
(note the extra double dash)

You'll need to delete the yarn.lock file as you indicate there, as the lock is generated with the fully-qualified URL's. I believe's it on their roadmap to change this behavior so the registry config will trump the lock file but for now I believe that's indeed how it works.

**Comment by jglick** [comment]
i.e.

```bash
PATH=$(pwd)/node:$(pwd)/node/yarn/dist/bin:$PATH yarn config set -- --registry https://repo.jenkins-ci.org/api/npm/npm/
```

**Comment by cliffmeyers** [comment]
"yarn" script should also be available at ./node/yarn I believe if you just want to invoke it directly

**Comment by jglick** [comment]
Yes that is what the above command does.

**Pull request merged**
